#!/usr/bin/env node
// Reads shared/app-config.ts, emits an idempotent SQL seed migration that UPSERTs
// each top-level key of APP_CONFIG into the app_config table as jsonb.

import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')
const srcConfig = resolve(repoRoot, 'shared/app-config.ts')
const outMigration = resolve(repoRoot, 'supabase/migrations/20260509000001_app_config_seed.sql')

// Compile shared/app-config.ts to a temp JS module and import it.
const tmp = resolve(repoRoot, 'node_modules/.cache/app-config.mjs')
mkdirSync(dirname(tmp), { recursive: true })
await build({
  entryPoints: [srcConfig],
  outfile: tmp,
  format: 'esm',
  platform: 'node',
  bundle: true,
  logLevel: 'error',
})
const { APP_CONFIG } = await import(tmp + '?ts=' + Date.now())

// Emit one UPSERT per top-level key.
// Use a dollar-quoted tag derived from the key to avoid any escaping concerns
// with quotes, backslashes, or Unicode line separators in the JSON payload.
const stmts = Object.entries(APP_CONFIG)
  .map(([key, value]) => {
    const json = JSON.stringify(value)
    const tag = `cfg_${key}`
    return `INSERT INTO public.app_config(key, value) VALUES ('${key}', $${tag}$${json}$${tag}$::jsonb)
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;`
  })
  .join('\n\n')

const header = `-- AUTO-GENERATED by scripts/gen-config.mjs from shared/app-config.ts
-- DO NOT EDIT BY HAND. Run \`pnpm gen:config\` to regenerate.

`

writeFileSync(outMigration, header + stmts + '\n')
console.log('Wrote', outMigration)
